version: "3"

services:
  database:
    image: mysql:8.0.30
    container_name: dockermysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=hackernews
      - MYSQL_ROOT_PASSWORD=dbpass
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - api-tier

  mongo:
    image: mongo:5.0
    container_name: dockermongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - api-tier
    ports:
      - "27017:27017"

  graph-api:
    container_name: docker-graph-api
    image: oscaralmgren/graphql-hackernews:busybox-0.2
    ports:
      - "8080:8080"
    networks:
      - api-tier
    depends_on:
            database:
                condition: service_healthy

networks:
  api-tier: {}